ProjectMVC2/Controllers/UserInsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectMVC2.Models;
using System.IO;

namespace ProjectMVC2.Controllers
{
    public class UserInsController : Controller
    {

        MVCProject2Entities dbobj = new MVCProject2Entities();
        // GET: UserIns
        public ActionResult UserLoad()
        {
            return View();
        }
        public ActionResult UserClick(UserInsert clsobj, HttpPostedFileBase file1, HttpPostedFileBase file2)
        {
            if (ModelState.IsValid)
            {
                if (file1.ContentLength > 0)
                {
                    string fname = Path.GetFileName(file1.FileName);
                    var s = Server.MapPath("~/photos");
                    string pa = Path.Combine(s, fname);
                    file1.SaveAs(pa);

                    var photopath = Path.Combine("~\\photos", fname);
                    clsobj.Photo = photopath;

                }
                if (file2.ContentLength > 0)
                {
                    string rname = Path.GetFileName(file2.FileName);
                    var s1 = Server.MapPath("~/resume");
                    string re = Path.Combine(s1, rname);
                    file2.SaveAs(re);

                    var resumepath = Path.Combine("~\\resume", rname);
                    clsobj.Resume = resumepath;
                }

                var getmaxid = dbobj.sp_logmaxid().FirstOrDefault();
                int mid = Convert.ToInt32(getmaxid);
                int regid = 0;
                if (mid == 0)
                {
                    regid = 1;
                }
                else
                {
                    regid = mid + 1;
                }
                dbobj.sp_userreg(regid, clsobj.Name, clsobj.Age, clsobj.Address, clsobj.Phone, clsobj.Email, clsobj.Qualification, clsobj.Experience, clsobj.Skill, clsobj.Photo, clsobj.Resume);
                dbobj.sp_logg(regid, clsobj.Uusername, clsobj.Upassword, "User");
                clsobj.UMsg = "User Inserted";
                return View("UserLoad", clsobj);
            }
            return View("UserLoad",clsobj);
        }
    }
}

ProjectMVC2/Views/UserIns/UserLoad.cshtml
@model ProjectMVC2.Models.UserInsert
@{
    ViewBag.Title = "UserLoad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User Registration</h2>
<div>
    @using (Html.BeginForm("UserClick", "UserIns", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {


        <div>
            <label>Name: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Name)
            @Html.ValidationMessageFor(m => m.Name)
        </div>

        <div>
            <label>Age: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Age)
            @Html.ValidationMessageFor(m => m.Age)
        </div>


        <div>
            <label>Address: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Address)
            @Html.ValidationMessageFor(m => m.Address)
        </div>


        <div>
            <label>Phone: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Phone)
            @Html.ValidationMessageFor(m => m.Phone)
        </div>



        <div>
            <label>Email: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Email)
            @Html.ValidationMessageFor(m => m.Email)
        </div>




        <div>
            <label>Qualification: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Qualification)

        </div>


        <div>
            <label>Experience: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Experience)

        </div>



        <div>
            <label>Skills: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Skill)

        </div>



        <div>
            <label>Photo: </label>
        </div>
        <div>
            @Html.TextBox("file1", "", new { Type = "file" })
        </div>



        <div>
            <label>Resume: </label>
        </div>
        <div>
            @Html.TextBox("file2", "", new { Type = "file" })
        </div>


        <div>
            <label>Username </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Uusername)
            @Html.ValidationMessageFor(m => m.Uusername)
        </div>

        <div>
            <label>Password </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Upassword)
            @Html.ValidationMessageFor(m => m.Upassword)
        </div>

        <div>
            <label> Confirm Password </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Uconfirmpassword)
            @Html.ValidationMessageFor(m => m.Uconfirmpassword)
        </div>

        <div>
            <input type="submit" value="Register" />
            @Html.DisplayFor(m => m.UMsg)
        </div>


    }
</div>
    