ProjectMVC2/Models/JobSearch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjectMVC2.Models
{
    public class JobSearch
    {

        public JobSearch()
        {
            selectjob = new List<jsearch>();
            insertsearch = new jsearch();
        }
        public jsearch insertsearch { get; set; }
        public List<jsearch> selectjob { get; set; }
    }
    public class jsearch
    {
        public int Jobid { get; set; }
        public int Company_id { get; set; }

        public string Jsskills { get; set; }

        public string Jsexperience { get; set; }
        public string Jobstatus { get; set; }
        public string Lastdate { get; set; }
        public string JobLocation { get; set; }
    }

}

ProjectMVC2/Controllers/JobDescriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using ProjectMVC2.Models;
using System.Data;
using System.IO;
using System.Configuration;

namespace ProjectMVC2.Controllers
{

    public class JobDescriptionController : Controller
    {
        MVCProject2Entities dbobj = new MVCProject2Entities();

        // GET: JobDescription
        public ActionResult JobDetails(int cid, int jid)
        {
            Session["cid"] = cid;
            Session["jid"] = jid;
            
            int jid1 = Convert.ToInt32(Session["jid"]);
            int cid1 = Convert.ToInt32(Session["cid"]);
            var job = dbobj.Jobtabs.FirstOrDefault(j => j.Jobid == jid1 && j.Cid == cid1);
            if (job == null)
            {
                return HttpNotFound();
            }

            var jobDetail = new JobDetailsCls
            {
                Jobid = job.Jobid,
                Company_id = job.Cid,
                Jsskills = job.JSkills,
                Jsexperience = job.JExperience,
                Jobstatus = job.JStatus,
                Lastdate = job.Date,
                JobLocation = job.JLocation
            };
            return View(jobDetail);
        }

        [HttpPost]
        public ActionResult ApplyClick(ApplyNow obj, HttpPostedFileBase file)
        {

            obj.Jobid = Convert.ToInt32(Session["jid"]);
            int userId = Convert.ToInt32(Session["sessionID"]);

            if (file != null && file.ContentLength > 0)
            {
                string fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/resume"), fileName);
                file.SaveAs(path);

                string resumepath = Path.Combine("~\\resume", fileName);
                obj.CV = resumepath;

                // Set AppStatus to a default value
                obj.AppStatus = "Pending";
   
                dbobj.sp_appdata(obj.Userid = userId, obj.Jobid, obj.CV, obj.Date = DateTime.Now.ToString(), obj.AppStatus);
                obj.ApplyMsg = "Applied Successfully";
                ViewBag.Message = obj.ApplyMsg;
            }
            else
            {
                ViewBag.Message = "Please upload a valid CV.";
            }

            return View();
        }

    }
}

ProjectMVC2/Controllers/JobSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectMVC2.Models;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using System.IO;

namespace ProjectMVC2.Controllers
{
    public class JobSearchController : Controller
    {
        MVCProject2Entities dbobj = new MVCProject2Entities();
        // GET: JobSearch
        public ActionResult SearchLoad()
        {
            return View(GetData());
        }
        private JobSearch GetData()
        {
            var Joblist = new JobSearch();
            List<string> lst = new List<string>();
            var job = dbobj.Jobtabs.ToList();
            foreach (var e in job)
            {
                var jobcls = new jsearch();
                jobcls.Jobid = e.Jobid;
                jobcls.Company_id = e.Cid;
                jobcls.Jsskills = e.JSkills;
                jobcls.Jsexperience = e.JExperience;
                jobcls.Jobstatus = e.JStatus;
                jobcls.Lastdate = e.Date;
                jobcls.JobLocation = e.JLocation;
                Joblist.selectjob.Add(jobcls);

                var s = jobcls.Jsskills;
                lst.Add(s);
                TempData["ski"] = string.Join(" ", lst);
            }
            return Joblist;
        }

        public ActionResult SearchClick(JobSearch clsobj)
        {
            string qry = "";
            if (!string.IsNullOrWhiteSpace(clsobj.insertsearch.Jsexperience))
            {
                qry += " and JExperience like '%" + clsobj.insertsearch.Jsexperience + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertsearch.Jsskills))
            {
                qry += " and JSkills like '%" + clsobj.insertsearch.Jsskills + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertsearch.JobLocation))
            {
                qry += " and JLocation like '%" + clsobj.insertsearch.JobLocation + "%'";
            }
            return View("SearchLoad", getdata1(clsobj, qry));
        }

        private JobSearch getdata1(JobSearch clsobj, string qry)
        {
            using (var con = new SqlConnection(@"server=GOWTHAMPC\SQLEXPRESS;database=MVCProject2;integrated security=true")) //(ConfigurationManager.ConnectionStrings["test"].ConnectionString))
            {
                SqlCommand cmd = new SqlCommand("sp_searchjobs", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@qry", qry);
                con.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                var joblist2 = new JobSearch();
                while (dr.Read())
                {
                    var jobcls = new jsearch();
                    jobcls.Company_id = Convert.ToInt32(dr["Cid"].ToString());
                    jobcls.Jsskills = dr["JSkills"].ToString();
                    jobcls.Jsexperience = dr["JExperience"].ToString();
                    jobcls.JobLocation = dr["JLocation"].ToString();
                    jobcls.Jobstatus = dr["JStatus"].ToString();
                    jobcls.Lastdate = dr["Date"].ToString();

                    joblist2.selectjob.Add(jobcls);
                }
                con.Close();
                return joblist2;

            }
        }

    }
}

  

ProjectMVC2/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Core.Objects;
using ProjectMVC2.Models;

namespace ProjectMVC2.Controllers
{
    public class LogInController : Controller
    {

        MVCProject2Entities dbobj = new MVCProject2Entities();
        // GET: LogIn
        public ActionResult LoginLoad()
        {
            return View();
        }
        public ActionResult UserHome()
        {
            return View();
        }
        public ActionResult CompanyHome()
        {
            return View("~/Views/JobIn/JobLoad.cshtml");
        }
        public ActionResult LoginClick(LoginCls objcls)
        {

            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("lgsts", typeof(int));
                dbobj.sp_logcount(objcls.Luname,objcls.Lpassword, op);
                int val = Convert.ToInt32(op.Value.ToString());
                if (val == 1)
                {
                    var sessionID = dbobj.loginid(objcls.Luname, objcls.Lpassword).FirstOrDefault();
                    Session["sessionID"] = sessionID;
                    var logtypee = dbobj.sp_logtype(objcls.Luname, objcls.Lpassword).FirstOrDefault();
                    if (logtypee == "User")
                    {
                        return RedirectToAction("UserHome");
                    }
                    else if (logtypee == "Company")
                    {
                        return RedirectToAction("CompanyHome");
                    }
                }
                else
                {
                    ModelState.Clear();
                    objcls.Lmsg = "Invalid login";
                    return View("LoginLoad", objcls);
                }

            }

            return View("LoginLoad",objcls);
        }
    }
}

ProjectMVC2/Views/JobSearch/SearchLoad.cshtml
@model ProjectMVC2.Models.JobSearch
@{
    ViewBag.Title = "SearchLoad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Job Search</h2>
<div>
    @using (Html.BeginForm("SearchLoad", "JobSearch", FormMethod.Post))
    {
        <div class="form-group">
            <label for="skills">Skills:</label>
            @Html.TextBoxFor(m => m.insertsearch.Jsskills)
        </div>
                        <div class="form-group">
                            <label for="experience">Experience:</label>
                            @Html.TextBoxFor(m => m.insertsearch.Jsexperience)
                        </div>
                                        <div class="form-group">
                                            <label for="location">Location:</label>
                                            @Html.TextBoxFor(m => m.insertsearch.JobLocation)
                                        </div>
                                                        <button type="submit" class="btn btn-primary">Search</button>
                                                    }
</div>
<div>
    @using (Html.BeginForm("SearchLoad", "JobSearch", FormMethod.Get))
    {
        if (Model != null)
        {
            if (Model.selectjob != null && Model.selectjob.Count != 0)
            {
                <table class="table">
                    <tr>
                    </tr>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(m => m.insertsearch.Company_id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertsearch.Jsskills)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertsearch.Jsexperience)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertsearch.JobLocation)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertsearch.Jobstatus)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertsearch.Lastdate)
                        </th>
                        <th>
                            Link
                        </th>
                    </tr>


                    @foreach (var item in Model.selectjob)
                    {
                        <tr>
                            <td>
                                <label>Job Title</label>
                                @Html.DisplayFor(modelItem => item.Company_id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Jsskills)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Jsexperience)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.JobLocation)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Jobstatus)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Lastdate)
                            </td>
                            <td>

                                @Html.ActionLink("Apply Now", "JobDetails", "JobDescription", new { cid = item.Company_id, jid = item.Jobid }, null)
                            </td>

                        </tr>
                    }

                </table>
            }
            else
            {
                <script>
                    alert('no data found');
                </script>
            }
        }
    }
    <div>
        @Html.ActionLink("Back to Home Page", "UserHome", "LogIn")

    </div>


</div>