ProjectMVC2/Controllers/JobInController.cs
using ProjectMVC2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace ProjectMVC2.Controllers
{
   
    public class JobInController : Controller
    {
        MVCProject2Entities dbobj = new MVCProject2Entities();
        // GET: JobIn
        public ActionResult JobLoad()
        {
            return View();
        }
        public ActionResult JobClick(JobInsert clsobj)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    //clsobj.Jdate = DateTime.Now.AddDays(10);
                    clsobj.Jstatus = "Available";

                    if (Session["sessionID"] != null)
                    {
                        int sessionID = Convert.ToInt32(Session["sessionID"]);
                        dbobj.sp_jobadd(sessionID, clsobj.Jtitle, clsobj.Jexperience, clsobj.Jskill, clsobj.Jvacancy, clsobj.Jdate, clsobj.Jstatus, clsobj.Jlocation);
                        clsobj.Jmsg = "Job added successfully!";
                    }
                    else
                    {
                        clsobj.Jmsg = "Session expired. Please log in again.";
                    }
                }
                catch (Exception ex)
                {
                    clsobj.Jmsg = "Error adding job: " + ex.Message;
                    if (ex.InnerException != null)
                    {
                        clsobj.Jmsg += " Inner Exception: " + ex.InnerException.Message;
                    }
                    // Log the exception for further investigation
                    // Example: logger.Error("Error adding job", ex);
                }

            }
            else
            {
                clsobj.Jmsg = "Invalid";
            }
            return View("JobLoad",clsobj);
        }
    }
}

ProjectMVC2/Controllers/JobSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectMVC2.Models;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using System.IO;

namespace ProjectMVC2.Controllers
{
    public class JobSearchController : Controller
    {
        MVCProject2Entities dbobj = new MVCProject2Entities();
        // GET: JobSearch
        public ActionResult SearchLoad()
        {
            return View(GetData());
        }
        private JobSearch GetData()
        {
            var Joblist = new JobSearch();
            List<string> lst = new List<string>();
            var job = dbobj.Jobtabs.ToList();
            foreach (var e in job)
            {
                var jobcls = new jsearch();
                jobcls.Jobid = e.Jobid;
                jobcls.Company_id = e.Cid;
                jobcls.Jsskills = e.JSkills;
                jobcls.Jsexperience = e.JExperience;
                jobcls.Jobstatus = e.JStatus;
                jobcls.Lastdate = e.Date;
                jobcls.JobLocation = e.JLocation;
                Joblist.selectjob.Add(jobcls);

                var s = jobcls.Jsskills;
                lst.Add(s);
                TempData["ski"] = string.Join(" ", lst);
            }
            return Joblist;
        }

        public ActionResult SearchClick(JobSearch clsobj)
        {
            string qry = "";
            if (!string.IsNullOrWhiteSpace(clsobj.insertsearch.Jsexperience))
            {
                qry += " and JExperience like '%" + clsobj.insertsearch.Jsexperience + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertsearch.Jsskills))
            {
                qry += " and JSkills like '%" + clsobj.insertsearch.Jsskills + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertsearch.JobLocation))
            {
                qry += " and JLocation like '%" + clsobj.insertsearch.JobLocation + "%'";
            }
            return View("SearchLoad", getdata1(clsobj, qry));
        }

        private JobSearch getdata1(JobSearch clsobj, string qry)
        {
            using (var con = new SqlConnection(@"server=GOWTHAMPC\SQLEXPRESS;database=MVCProject2;integrated security=true")) //(ConfigurationManager.ConnectionStrings["test"].ConnectionString))
            {
                SqlCommand cmd = new SqlCommand("sp_searchjobs", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@qry", qry);
                con.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                var joblist2 = new JobSearch();
                while (dr.Read())
                {
                    var jobcls = new jsearch();
                    jobcls.Company_id = Convert.ToInt32(dr["Cid"].ToString());
                    jobcls.Jsskills = dr["JSkills"].ToString();
                    jobcls.Jsexperience = dr["JExperience"].ToString();
                    jobcls.JobLocation = dr["JLocation"].ToString();
                    jobcls.Jobstatus = dr["JStatus"].ToString();
                    jobcls.Lastdate = dr["Date"].ToString();

                    joblist2.selectjob.Add(jobcls);
                }
                con.Close();
                return joblist2;

            }
        }

    }
}

  

ProjectMVC2/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Core.Objects;
using ProjectMVC2.Models;

namespace ProjectMVC2.Controllers
{
    public class LogInController : Controller
    {

        MVCProject2Entities dbobj = new MVCProject2Entities();
        // GET: LogIn
        public ActionResult LoginLoad()
        {
            return View();
        }
        public ActionResult UserHome()
        {
            return View();
        }
        public ActionResult CompanyHome()
        {
            return View("~/Views/JobIn/JobLoad.cshtml");
        }
        public ActionResult LoginClick(LoginCls objcls)
        {

            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("lgsts", typeof(int));
                dbobj.sp_logcount(objcls.Luname,objcls.Lpassword, op);
                int val = Convert.ToInt32(op.Value.ToString());
                if (val == 1)
                {
                    var sessionID = dbobj.loginid(objcls.Luname, objcls.Lpassword).FirstOrDefault();
                    Session["sessionID"] = sessionID;
                    var logtypee = dbobj.sp_logtype(objcls.Luname, objcls.Lpassword).FirstOrDefault();
                    if (logtypee == "User")
                    {
                        return RedirectToAction("UserHome");
                    }
                    else if (logtypee == "Company")
                    {
                        return RedirectToAction("CompanyHome");
                    }
                }
                else
                {
                    ModelState.Clear();
                    objcls.Lmsg = "Invalid login";
                    return View("LoginLoad", objcls);
                }

            }

            return View("LoginLoad",objcls);
        }
    }
}

ProjectMVC2/Views/LogIn/CompanyHome.cshtml
@model ProjectMVC2.Models.JobInsert
@{
    ViewBag.Title = "CompanyHome";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CompanyHome</h2>
<div>
    @using (Html.BeginForm("JobClick", "JobIn", FormMethod.Post, new { enctype = "multipart/form-data" }))

    {
        <div>
            <label>Job Title:</label>
            @Html.TextBoxFor(m => m.Jtitle)
        </div>

        <div>
            <label>Experience:</label>
            @Html.TextBoxFor(m => m.Jexperience)
        </div>

        <div>
            <label>Skill:</label>
            @Html.TextBoxFor(m => m.Jskill)
        </div>

        <div>
            <label>Vacancy:</label>
            @Html.TextBoxFor(m => m.Jvacancy)
        </div>

        <div>
            <label>Date:</label>
            @*@Html.TextBoxFor(m => m.date, new { @type = "date" })*@
            @Html.TextBoxFor(m=>m.Jdate)
        </div>

        <div>
            <input type="submit" value="Add Job" />
        </div>

        <div>
            @Html.DisplayFor(m => m.Jmsg)
        </div>
        <div>
            @Html.ActionLink("Back To Login", "LoginLoad", "LogIn")
        </div>
    }

</div>

ProjectMVC2/Views/LogIn/LoginLoad.cshtml
@model ProjectMVC2.Models.LoginCls
@{
    ViewBag.Title = "LoginLoad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login Here</h2>
<div>
    @using (Html.BeginForm("LoginClick", "LogIn", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {



        <div>
            <label>Username </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Luname)
            @Html.ValidationMessageFor(m => m.Luname)
        </div>

        <div>
            <label>Password </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Lpassword)
            @Html.ValidationMessageFor(m => m.Lpassword)
        </div>

        <div>
            <input type="submit" value="Login" />
            @Html.DisplayFor(m => m.Lmsg)
        </div>
    }
</div>

ProjectMVC2/Views/LogIn/UserHome.cshtml
@{
    ViewBag.Title = "UserHome";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UserHome</h2>


<div>
    @Html.ActionLink("Search Jobs", "SearchLoad", "JobSearch")
</div>