ProjectMVC2/Controllers/CompanyInController.cs
using ProjectMVC2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace ProjectMVC2.Controllers
{
    public class CompanyInController : Controller
    {
        MVCProject2Entities dbobj = new MVCProject2Entities();
        // GET: CompanyIn
        public ActionResult CompanyLoad()
        {
            return View();
        }

        public ActionResult CompanyClick(CompanyInsert clsobj)
        {

            if (ModelState.IsValid)
            {
                var getmaxid = dbobj.sp_logmaxid().FirstOrDefault();
                int mid = Convert.ToInt32(getmaxid);
                int regid = 0;
                if (mid == 0)
                {
                    regid = 1;
                }
                else
                {

                    regid = mid + 1;
                }
                dbobj.sp_company(regid, clsobj.Cname, clsobj.Caddr, clsobj.Cphone, clsobj.Cemail, clsobj.Cwebsite, clsobj.Clocation);
                dbobj.sp_logg (regid, clsobj.Username, clsobj.Password, "Company");
                clsobj.Msg = "Inserted";
                return View("CompanyLoad", clsobj);
            }
            return View("CompanyLoad", clsobj);

        }
    }
}

ProjectMVC2/Views/CompanyIn/CompanyLoad.cshtml
@model ProjectMVC2.Models.CompanyInsert
@{
    ViewBag.Title = "CompanyLoad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Company Registration</h2>
<div>
    @using (Html.BeginForm("CompanyClick", "CompanyIn", FormMethod.Post,new { enctype = "multipart/form-data" }))
    {


        <div>
            <label>Name: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Cname)
            @Html.ValidationMessageFor(m => m.Cname)
        </div>

        <div>
            <label>Address: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Caddr)
            @Html.ValidationMessageFor(m => m.Caddr)
        </div>


        <div>
            <label>Phone: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Cphone)
            @Html.ValidationMessageFor(m => m.Cphone)
        </div>


        <div>
            <label>Email: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Cemail)
            @Html.ValidationMessageFor(m => m.Cemail)
        </div>


        <div>
            <label>Website: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Cwebsite)
            @Html.ValidationMessageFor(m => m.Cwebsite)
        </div>


        <div>
            <label>Location: </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Clocation)
            @Html.ValidationMessageFor(m => m.Clocation)


        </div>

        <div>
            <label>Username </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Username)
            @Html.ValidationMessageFor(m => m.Username)
        </div>

        <div>
            <label>Password </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Password)
            @Html.ValidationMessageFor(m => m.Password)
        </div>

        <div>
            <label> Confirm Password </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.ConfirmPassword)
            @Html.ValidationMessageFor(m => m.ConfirmPassword)
        </div>

        <div>
            <input type="submit" value="Register" />
            @Html.DisplayFor(m => m.Msg)
        </div>

    }

</div>